---
title: "Proposed title: The Noisy Work of Uncertainty Visualisation Research"
author: 
  - name: Harriet Mason
  - name: Dianne Cook
  - name: Sarah Goodwin
  - name: Emi Tanaka
  - name: Susan VanderPlas
bibliography: summary.bib
nocite: |
  @*
toc: false
number-sections: true
latex-clean: true
format: pdf
fig-valign: bottom
cap-location: bottom
editor_options: 
  chunk_output_type: console
---

# Rationale 

Better ways of including representation of the uncertainty in a data visualisation is a focus of recent research activity. A problem with the current literature is that there is a lack of clarity about the definition of uncertainty, and what it means to represent it in a plot. This confusion can also be seen in the literature describing experiments on the effectiveness of different uncertainty representation. The purpose of this review article is to summarise the current literature, provide workable definitions, and illustrate these with examples. It is hoped that it will be useful for guiding new graphics methodology and experimental research. 

<!-- XXX needs re-writing: The literature on uncertainty visualisation treats the definition and purpose to be self evident which results in a large amount of conflicting information. This conflict largely stems from a conflation between uncertainty visualisations designed for to visualise uncertainty as signal and those used to visualise uncertainty as noise. We coin the term "signal suppression" to describe a visualisation that is designed for preventing false conclusions, as the approach demands that the signal (i.e. the collective take away of the estimates) is suppressed by the noise (i.e. the variance on those estimates). We argue that the current standards in visualisation suggest that uncertainty visualisations designed to extract uncertain information should not be considered uncertainty visualisations at all. Therefore, future work should focus on signal suppression. Effective signal suppression requires us to communicate the signal and the noise as a single "validity of signal" variable, and doing so proves to be difficult with current methods. We illustrate current approaches to uncertainty visualisation by showing how they would change the visual apprearance of a choropleth map. These maps allow us to see why some methods succeed at signal suppression, while others fall short. Evaluating visualisations on how well they perform signal suppression also proves to be difficult, as it involves measuring the effect of noise, a variable we typically try to ignore. We suggest authors use qualitative studies or compare uncertainty visualisations to the relevant hypothesis tests. -->

# Outline

1. Common uses of the term "uncertainty visualisation": Here we will provide some background to the use of the term "uncertainty visualisation" and tie it to statistical definitions of uncertainty.
2. Dangers of ignoring uncertainty representation in a visualisation. This part motivates the reason for the importance of this area of research. 
3. Review of current approaches to representing uncertainty in plots, as gathered from discipline journals in information visualisation, statistics, environmental science and psychology. 
4. Review of literature describing experiments testing effectiveness of different representations. The information visualisation literature is especially prolific in describing experiments assessing the relative merits of different uncertainty visualisations, and this section will critically summarise these efforts, and propose refining of procedures. 
5. Examples: 

- Comparing distributions with the purpose to illustrate definitions of uncertainty, and distinction between representations of signal vs noise. It is also a place where software exists providing some good choices but are not yet sufficient.
- Spatial data poses substantial challenges because of the difficulties of using the page for the map coordinates, and hence little room for representing uncertainty. It also has been a place with useful recent work, providing some good solutions. 

6. Recommendations for research directions. Here we will gather the discussion into some suggestions for framing new work, developing methodology and designing experiments. 

# References
